services:
  node:
    image: node:20-alpine
    container_name: laravel_node
    profiles:
      - dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel
    depends_on:
      - app
